# Generated by Django 3.1.2 on 2020-10-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facciones', '0003_auto_20201027_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castle',
            name='image',
            field=models.ImageField(upload_to='uploads/castle'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='image',
            field=models.ImageField(upload_to='uploads/faction'),
        ),
    ]
