# Generated by Django 3.1.2 on 2020-10-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facciones', '0004_auto_20201027_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastlogin',
            field=models.DateTimeField(null=True),
        ),
    ]
